name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run-install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Coverage
        run: pnpm coverage
      - name: Generate badge
        uses: ImBIOS/lcov-coverage-badge@v1
        with:
          coverage-file: coverage/lcov.info
          badge-path: .github/badges/coverage.svg
          github-token: ${{ secrets.GITHUB_TOKEN }}
