name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run-install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Coverage
        run: pnpm coverage
      - name: Upload coverage
        uses: actions/upload-coverage@v1
        with:
          coverage-file: coverage/coverage-final.json
          token: ${{ github.token }}
